language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - 10

script:
  - npm run test && npm run build
after_success:
  - npm run report-coverage
